<#
.SYNOPSIS
    Додає Traefik-інтеграцію до існуючого Docker-проєкту.
.DESCRIPTION
    Створює override-файл з Traefik labels та мережею, не змінюючи оригінальний compose.yaml.
.PARAMETER ProjectPath
    Шлях до директорії проєкту.
.PARAMETER Domain
    Домен для проєкту (наприклад, myapp.home.arpa).
.PARAMETER Service
    Ім'я сервісу в compose.yaml.
.PARAMETER InternalPort
    Внутрішній порт контейнера.
.EXAMPLE
    .\scripts\add-project.ps1 -ProjectPath "E:\Projects\myapp" -Domain "myapp.home.arpa" -Service "web" -InternalPort 8080
#>

param(
    [Parameter(Mandatory=$true)][string]$ProjectPath,
    [Parameter(Mandatory=$true)][string]$Domain,
    [string]$Service,
    [int]$InternalPort = 0
)

$ErrorActionPreference = "Stop"
$rootDir = Resolve-Path -Path "$PSScriptRoot\.."

if (-not (Test-Path $ProjectPath)) {
    Write-Host "[ПОМИЛКА] Директорiя $ProjectPath не iснує." -ForegroundColor Red; exit 1
}

$composeFile = Join-Path $ProjectPath "compose.yaml"
if (-not (Test-Path $composeFile)) { $composeFile = Join-Path $ProjectPath "docker-compose.yml" }
if (-not (Test-Path $composeFile)) { Write-Host "[ПОМИЛКА] У $ProjectPath не знайдено compose-файл." -ForegroundColor Red; exit 1 }

$yaml = Get-Content $composeFile -Raw
$services = @()
$lines = Get-Content $composeFile
$inServices = $false
foreach ($line in $lines) {
    if ($line -match '^services:') { $inServices = $true; continue }
    if ($inServices -and $line -match '^\S' -and $line -notmatch '^  ') { $inServices = $false }
    if ($inServices -and $line -match '^  (\w[\w-]*):') { $services += $matches[1] }
}

if ($services.Count -eq 0) { Write-Host "[ПОМИЛКА] У compose-файлi немає сервісів." -ForegroundColor Red; exit 1 }

if (-not $Service) {
    if ($services.Count -eq 1) { $Service = $services[0] }
    else {
        Write-Host "Доступні сервіси:" -ForegroundColor Cyan
        $services | ForEach-Object { Write-Host "  - $_" }
        $Service = Read-Host "Вкажіть ім'я сервісу"
    }
}

if ($services -notcontains $Service) { Write-Host "[ПОМИЛКА] Сервіс '$Service' не знайдено." -ForegroundColor Red; exit 1 }

if ($InternalPort -eq 0) {
    $InternalPort = [int](Read-Host "Внутрішній порт контейнера (Enter = 80)")
    if ($InternalPort -eq 0) { $InternalPort = 80 }
}

$routerName = $Service -replace '[_ ]', '-'
$projectName = [System.IO.Path]::GetFileName($ProjectPath)

Write-Host ""
Write-Host "Параметри інтеграції:" -ForegroundColor Cyan
Write-Host "  Проєкт:     $projectName"
Write-Host "  Домен:      $Domain"
Write-Host "  Сервіс:     $Service"
Write-Host "  Порт:       $InternalPort"
Write-Host "  Router:     $routerName"
Write-Host ""

$overrideContent = @"
# Traefik integration for $projectName
# Generated by docker-local-hosting add-project
# Використання: docker compose -f compose.yaml -f compose.traefik.override.yaml up -d

services:
  $Service:
    networks:
      - local-hosting
    labels:
      traefik.enable: "true"
      traefik.docker.network: "`${LOCAL_HOSTING_NETWORK:-local-hosting}"
      traefik.http.routers.$routerName.rule: "Host(`$Domain`)"
      traefik.http.routers.$routerName.entrypoints: "websecure"
      traefik.http.routers.$routerName.tls: "true"
      traefik.http.services.$routerName.loadbalancer.server.port: "$InternalPort"

networks:
  local-hosting:
    external: true
    name: "`${LOCAL_HOSTING_NETWORK:-local-hosting}"
"@

$overrideFile = Join-Path $ProjectPath "compose.traefik.override.yaml"
if (Test-Path $overrideFile) {
    $existing = Get-Content $overrideFile -Raw
    if ($existing -eq $overrideContent) {
        Write-Host "[OK] Файл $overrideFile вже актуальний." -ForegroundColor Green
    } else {
        Write-Host "[УВАГА] Файл $overrideFile iснує, але вiдрiзняється." -ForegroundColor Yellow
        Write-Host "Поточний вмiст:" -ForegroundColor Yellow
        Write-Host $existing -ForegroundColor Gray
        $response = Read-Host "Перезаписати? (Y/N)"
        if ($response -eq "Y" -or $response -eq "y") {
            Set-Content -Path $overrideFile -Value $overrideContent
            Write-Host "[OK] $overrideFile перезаписано." -ForegroundColor Green
        } else { Write-Host "Пропущено." -ForegroundColor Yellow }
    }
} else {
    Set-Content -Path $overrideFile -Value $overrideContent
    Write-Host "[OK] Створено $overrideFile" -ForegroundColor Green
}

$envFile = Join-Path $ProjectPath ".env.traefik"
if (-not (Test-Path $envFile)) {
    $envContent = @"
# Traefik integration for $projectName
APP_DOMAIN=$Domain
APP_INTERNAL_PORT=$InternalPort
LOCAL_HOSTING_NETWORK=local-hosting
"@
    Set-Content -Path $envFile -Value $envContent
    Write-Host "[OK] Створено $envFile" -ForegroundColor Green
}

Write-Host ""
Write-Host "Запустiть проєкт:" -ForegroundColor Cyan
Write-Host "  cd $ProjectPath" -ForegroundColor Cyan
Write-Host "  docker compose -f compose.yaml -f compose.traefik.override.yaml --env-file .env.traefik up -d" -ForegroundColor Cyan
Write-Host ""
Write-Host "Не забудьте додати домен у hosts:" -ForegroundColor Yellow
Write-Host "  127.0.0.1 $Domain" -ForegroundColor Yellow
