#!/bin/sh
# Додає Traefik-інтеграцію до існуючого Docker-проєкту.
# Створює override-файл, не змінюючи оригінальний compose.yaml.
# Використання:
#   ./scripts/add-project.sh <project-path> <domain> [service] [port]

set -Eeuo pipefail

project_path="${1:-}"
domain="${2:-}"
service="${3:-}"
port="${4:-80}"

if [ -z "$project_path" ] || [ -z "$domain" ]; then
    echo "Використання: $0 <шлях_до_проєкту> <домен> [сервіс] [порт]" >&2
    echo "Приклад: $0 ~/projects/myapp myapp.home.arpa web 8080" >&2
    exit 1
fi

if [ ! -d "$project_path" ]; then
    echo "[ПОМИЛКА] Директорія $project_path не існує." >&2
    exit 1
fi

compose_file="$project_path/compose.yaml"
[ ! -f "$compose_file" ] && compose_file="$project_path/docker-compose.yml"
if [ ! -f "$compose_file" ]; then
    echo "[ПОМИЛКА] У $project_path не знайдено compose-файл." >&2
    exit 1
fi

project_name=$(basename "$project_path")

router_name=$(echo "$service" | sed 's/[_ ]/-/g')
[ -z "$router_name" ] && router_name="$project_name"

override_file="$project_path/compose.traefik.override.yaml"
cat > "$override_file" <<EOF
# Traefik integration for $project_name
# Generated by docker-local-hosting add-project
# Використання: docker compose -f compose.yaml -f compose.traefik.override.yaml up -d

services:
  $service:
    networks:
      - local-hosting
    labels:
      traefik.enable: "true"
      traefik.docker.network: "\${LOCAL_HOSTING_NETWORK:-local-hosting}"
      traefik.http.routers.$router_name.rule: "Host(\`$domain\`)"
      traefik.http.routers.$router_name.entrypoints: "websecure"
      traefik.http.routers.$router_name.tls: "true"
      traefik.http.services.$router_name.loadbalancer.server.port: "$port"

networks:
  local-hosting:
    external: true
    name: "\${LOCAL_HOSTING_NETWORK:-local-hosting}"
EOF

echo "[OK] Створено $override_file"

env_file="$project_path/.env.traefik"
cat > "$env_file" <<EOF
# Traefik integration for $project_name
APP_DOMAIN=$domain
APP_INTERNAL_PORT=$port
LOCAL_HOSTING_NETWORK=local-hosting
EOF

echo "[OK] Створено $env_file"
echo ""
echo "Запустіть проєкт:"
echo "  cd $project_path"
echo "  docker compose -f compose.yaml -f compose.traefik.override.yaml --env-file .env.traefik up -d"
echo ""
echo "Не забудьте додати домен у hosts:"
echo "  127.0.0.1 $domain"
