<#
.SYNOPSIS
    Додає зовнішній сервіс (не Docker) до Traefik через File Provider.
.DESCRIPTION
    Створює YAML-файл у config/traefik/dynamic/services/ з router i service.
    Traefik пiдхоплює змiни без restart (watch: true).
    Atomic write: temp file -> rename.
.PARAMETER Name
    Унiкальне iм`'я сервiсу.
.PARAMETER Domain
    Домен для доступу.
.PARAMETER Url
    URL бекенда (наприклад, http://192.168.1.50:9000).
.EXAMPLE
    .\scripts\add-external-service.ps1 -Name camera -Domain camera.home.arpa -Url http://192.168.1.50:9000
#>

param(
    [Parameter(Mandatory=$true)][string]$Name,
    [Parameter(Mandatory=$true)][string]$Domain,
    [Parameter(Mandatory=$true)][string]$Url
)

$ErrorActionPreference = "Stop"
$rootDir = Resolve-Path -Path "$PSScriptRoot\.."
$servicesDir = Join-Path $rootDir "config\traefik\dynamic"

if (-not (Test-Path $servicesDir)) { New-Item -ItemType Directory -Path $servicesDir -Force | Out-Null }

$fileName = "ext-$Name.yaml"
$filePath = Join-Path $servicesDir $fileName

$sb = New-Object System.Text.StringBuilder
$null = $sb.AppendLine("# External service: $Name")
$null = $sb.AppendLine("# Domain: $Domain")
$null = $sb.AppendLine("# Backend: $Url")
$null = $sb.AppendLine("# Auto-generated by add-external-service")
$null = $sb.AppendLine("")
$null = $sb.AppendLine("http:")
$null = $sb.AppendLine("  routers:")
$null = $sb.AppendLine("    ${Name}:")
$bt = [char]96
$null = $sb.AppendLine("      rule: ""Host($bt$Domain$bt)""")
$null = $sb.AppendLine("      entrypoints:")
$null = $sb.AppendLine("        - websecure")
$null = $sb.AppendLine("      service: ${Name}")
$null = $sb.AppendLine("      tls: true")
$null = $sb.AppendLine("")
$null = $sb.AppendLine("  services:")
$null = $sb.AppendLine("    ${Name}:")
$null = $sb.AppendLine("      loadBalancer:")
$null = $sb.AppendLine("        servers:")
$null = $sb.AppendLine("          - url: ""$Url""")
$null = $sb.AppendLine("        passHostHeader: true")

$yamlContent = $sb.ToString()

$tempPath = [System.IO.Path]::GetTempFileName()
[System.IO.File]::WriteAllText($tempPath, $yamlContent)

if (Test-Path $filePath) { Remove-Item $filePath -Force }
Move-Item -Path $tempPath -Destination $filePath -Force

Write-Host "[OK] Created $filePath" -ForegroundColor Green
Write-Host "Service $Name available at https://$Domain" -ForegroundColor Green
Write-Host "Traefik picks up changes without restart (watch: true)." -ForegroundColor Cyan
Write-Host ""
Write-Host "Add to hosts file:" -ForegroundColor Yellow
Write-Host "  127.0.0.1 $Domain" -ForegroundColor Yellow
