#!/bin/sh
# Додає зовнішній сервіс (не Docker) до Traefik через File Provider.
# Створює YAML у config/traefik/dynamic/services/.
# Traefik підхоплює зміни без restart.
# Використання:
#   ./scripts/add-external-service.sh <name> <domain> <url>
#   ./scripts/add-external-service.sh camera camera.home.arpa http://192.168.1.50:9000

set -Eeuo pipefail

name="${1:-}"
domain="${2:-}"
url="${3:-}"

if [ -z "$name" ] || [ -z "$domain" ] || [ -z "$url" ]; then
    echo "Використання: $0 <ім'я> <домен> <url>" >&2
    echo "Приклад: $0 camera camera.home.arpa http://192.168.1.50:9000" >&2
    exit 1
fi

root_dir="$(cd "$(dirname "$0")/.." && pwd)"
services_dir="$root_dir/config/traefik/dynamic/services"
mkdir -p "$services_dir"

file_path="$services_dir/$name.yaml"

# Atomic write: temp file -> rename
temp_file=$(mktemp)
cat > "$temp_file" <<EOF
# External service: $name
# Domain: $domain
# Backend: $url
# Auto-generated by add-external-service

http:
  routers:
    $name:
      rule: "Host(\`$domain\`)"
      entrypoints:
        - websecure
      service: $name
      tls: true

  services:
    $name:
      loadBalancer:
        servers:
          - url: "$url"
        passHostHeader: true
EOF

mv "$temp_file" "$file_path"
echo "[OK] Створено $file_path"
echo "Сервіс $name доступний за https://$domain"
echo ""
echo "Traefik підхопить зміни без restart (watch: true)."
echo ""
echo "Додайте у файл hosts:"
echo "  127.0.0.1 $domain"
